CREATE TABLE Broker
(
	BrokerID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(15) NOT NULL
);

CREATE TABLE Customer
(
	CustomerID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(30) NOT NULL,
	Amount INTEGER NOT NULL,
	BrokerID INTEGER NOT NULL,
	FOREIGN KEY(BrokerID ) REFERENCES Broker(BrokerID )
);